---
variables:
  DOCKERHUB_REPO_NAME: smtp
  GITHUB_REPO_NAME: ix-ai/smtp
  ENABLE_ARM64: 'true'
  ENABLE_ARMv7: 'true'
  ENABLE_386: 'true'

include:
  - project: 'ix.ai/ci-templates'
    file: '/bash-project.yml'
